accounts/admin.py, accounts/apps.py, accounts/models.py, accounts/tests.py, accounts/urls.py, accounts/views.py, booth/admin.py, booth/apps.py, booth/models.py, booth/tests.py, booth/urls.py, booth/views.py, linenow/settings.py, linenow/urls.py, waiting/admin.py, waiting/apps.py, waiting/models.py, waiting/tests.py, waiting/urls.py, waiting/views.py
초기 앱 세팅했습니다 ..
startapp만 한 상태이고 model 설계는 차차 해야 합니다.
모델 설계까지 하고 PR 닫을지는 고민방구네욤
-
-
없듬
=> ✨ Feat: setting apps

Dockerfile
=> ✨ Add: Dockerfile

linenow/settings.py
=> ✨ Feat: mysql 설정 추가

requirements.txt
=> 📝 Docs: Requirements 에 mysql 추가

linenow/settings.py
=> 🐛 Feat: Settings.py에 static root 추가

Dockerfile
=> 🐛 Fix : Docekrfile 수정

docker-compose.yml
docker-compose.yml 파일 작업물 git에 올립니다.
- 쏼라쏼라
```python
```
=> ✨ Feat: Docker-compose.yml 작성

docker-compose.yml
=> 🐛 Fix: docker-compose 수정

Dockerfile
컨테이너 내부에서 환경변수 사용할 수 있도록 수정
- 쏼라쏼라
```python
```
=> 💚 Fix: Dockerfile 수정

.github/workflows/django-deploy.yml
Reverts LINE-NOW/LINENOW-Server#25
=> Revert "Update django-deploy.yml"

docker-compose.yml
docker-compose로 redis, celery 2개의 컨테이너 추가하도록 했고, 환경변수로 관리하도록 했습니다.
환경 변수에서 Url 기본적으로 설정했는데 보안 이슈가 있다면 바꾸면 좋을 것 같습니다.
@dudtlstm 
- 쏼라쏼라
```python
```
- Resolved:
=> ✏️ Fix: docker-compose에 celery 추가

linenow/settings.py
=> 💚 Fix: Settings.py 수정

.github/workflows/django-deploy.yml
=> 💚 Fix: django-deploy.yml 수정

.github/workflows/django-deploy.yml
=> 💚 Fix: django-deploy 수정 pull_request_target 사용

.github/workflows/django-deploy.yml
=> 💚 Fix: database host 수정

.github/workflows/django-deploy.yml
=> 💚 Fix: CI 진행 분기에서 labeled 속성제거

docker-compose.yml, linenow/celery.py
celery 서버 다운될 시 restart 하도록 변경하고, broker 연결 재시도 활성화 기능 추가했습니다.
- 쏼라쏼라
```python
```
- Resolved:
=> 💚 Fix: celery.py docker-compose 재연결 활성화

docker-compose.yml
서버 로컬 데이터를 컨테이너 내부로 마운트하지 않도록 수정
- 쏼라쏼라
```python
```
=> 💚 Fix: Docker-compse 수정

.github/workflows/django-deploy.yml
=> 💚 Fix : docker 이미지 태그 수정

.github/workflows/django-deploy.yml
=> ✏️ Fix: deploy 파일 문법 수정

manager/models.py, manager/urls.py, manager/views.py
url에 booth_id가 있을 필요가 없어서 모두 제거했습니다.
=> 🩹 Fix: 관리자 url에서 불필요한 booth_id 뺌

Dockerfile
도커 파일에서 certbot 설치하는 부분 삭제했습니다.
- 쏼라쏼라
```python
```
=> 💚 Fix: 도커파일 certbot 부분 삭제

docker-compose.yml
=> 💚 Fix: ssl 인증서 마운트

waiting/models.py
=> 🩹 Fix: 입장 확정 API 수정

docker-compose.yml
=> 💚 Fix : docker-compose nginx ssl 인증서 관련 로직 수정

docker-compose.yml
=> 💚 Fix : redis 설정

docker-compose.yml
Reverts LINE-NOW/LINENOW-Server#69
=> Revert "💚 Fix : redis 설정"

linenow/settings.py
=> 🐛 Fix : cors allow origin

linenow/settings.py
=> 💚 Fix; Admin csrf 제외

linenow/settings.py
=> 🩹 Fix: settings.py 에 celery 추가

waiting/serializers.py
1. 나의 대기 상세에 해당 부스 전체 대기 팀 수 추가함
2. 3분 10분 타이머가 아닌 시간 더한 필드로 수정함
=> 🩹 Fix: 나의 대기 상세에 해당 부스 전체 대기 팀 수 추가 & 3분/10분 더한 필드로 수정

accounts/models.py, linenow/settings.py, manager/models.py, waiting/models.py, waiting/serializers.py, waiting/views.py
AbstractUser로 기존 User모델을 수정하여 전화번호 필드를 추가하였고, 사용하지 않는 필드들을 정리하였습니다. 
이미 기존 User 모델이 존재해서 자동으로 마이그레이션이 되지 않습니다.
DB를 한번 밀고 다시 적용해야 해서, 판단해주시고 리뷰 부탁 드립니다 !
이 방법이 별로인 것 같다면 OnetoOne으로 구현하겠습니다.
- 쏼라쏼라
```python
from django.db import models
from django.contrib.auth.models import AbstractUser
class User(AbstractUser):
first_name = None
last_name = None
password = None
phone_number = models.CharField(max_length=20, blank=False, name="phone_number")
nickname = models.CharField(max_length=20, blank=False, name="nickname")
```
=> 🐛 Fix: User 모델 필드 수정

.github/workflows/django-deploy.yml
=> ✅ Test commit

utils/permissions.py, waiting/views.py
일반유저인지 확인하고 로그인한 사용자가 맞는지 확인한 후 웨이팅 관련 기능 수행 가능
=> 🩹 Fix: 일반 유저 권한 추가

docker-compose.yml
=> ✏️ Fix: docker-compse 수정, media 설정 추가

accounts/views.py, linenow/settings.py
일반 사용자 토큰을 로컬 스토리지에 저장하는 방식으로 수정했습니다
기존 토큰 기반 인증은 삭제하였습니다.
쿠키에 저장되지 않고 응답으로 토큰 반환 됩니다.
```python
```
=> 🐛 Fix: 회원 쿠키기반 삭제 및 수정

accounts/urls.py, linenow/settings.py, manager/serializers.py, waiting/urls.py
manager/booth serializer 수정 및 프로젝트 urls.py trailing slash 삭제
- 쏼라쏼라
```python
```
- Resolved: #6
=> 🐛 Fix: manager/booth serializer 수정 및 프로젝트 urls.py trailing slash 삭제

manager/views.py
취소된 웨이팅은 뒤로 밀리도록 햇습니다.
- 쏼라쏼라
```python
```
- Resolved: #6
=> ✨ Feat: 부스 대기 목록 Ordering fields 구현

manager/views.py
착각했던 부분이 SMS를 다른곳에 적어서 그랬던 것 같습니다.
코드 원래대로 돌렸고, SMS전송을 call 부분으로 이동시켰습니다.
- 쏼라쏼라
```python
```
=> 🐛 Fix: call 문자메시지 발송 수정

booth/serializers.py
1. is_waiting : 상태 변경해도 잘 반영되게 수정
2. waiting_status : 대기를 여러 번 걸었을 때(즉, 취소하고 다시 걸기) 최신 status가 뜨도록 수정
=> 🩹 Fix: is_waiting, waiting_status 반영 잘 되게

manager/views.py, waiting/tasks.py
기획에서 요청 받아서 문자 내용 수정하였습니다.
- 쏼라쏼라
```python
```
=> 🐛 Fix: 문자 내용 수정

.github/workflows/django-deploy.yml, accounts/forms.py, accounts/urls.py, accounts/views.py, linenow/settings.py, utils/turnstile.py
클라우드플레어 turnstile 적용했습니다.
기존 dj-rest-auth register 을 커스텀해서 폼에서 먼저 토큰을 받고 함수를 통해 인증과정 거치고 맞다면 인증 보내주는 형식입니다.
제발 되길 빌면서
- 쏼라쏼라
```python
```
=> ✨ Feat: cloudflare turnstile 적용

waiting/views.py
=> 🩹 Fix: 한 웨이팅 '입장 확정' 시 다른 웨이팅 모두 취소

accounts/views.py, utils/turnstile.py
turnstile 관련한 로직 수정했습니다.
- 쏼라쏼라
```python
```
- Resolved:
=> 🐛 Fix: turnstile 관련 회원가입 폼 수정

booth/views.py
부스 정렬을 추가하였습니다.
1. 우선 '운영 상태'에 따라 정렬됩니다.
operating(운영 중인 부스) → 1
paused(대기 중지 상태인 부스) → 2
not_started(운영이 시작되지 않은 부스) → 3
finished(운영이 종료된 부스) → 4
2. '운영 상태'로 정렬된 후 '이름 순'으로 정렬됩니다.
3. 'waiting_count'로 정렬할 때는 '운영 상태'로 정렬 후, 대기 많은 순 - 대기 적은 순으로 정렬됩니다.
`/api/v1/booths`
`/api/v1/booths?ordering=-waiting_count`
`/api/v1/booths?ordering=waiting_count`
`/api/v1/booths?ordering=name`
```python
def get_queryset(self):
queryset = Booth.objects.annotate(
waiting_count=Count('waitings'),
is_operated_order=Case(
When(is_operated='operating', then=Value(1)),
When(is_operated='paused', then=Value(2)),
When(is_operated='not_started', then=Value(3)),
When(is_operated='finished', then=Value(4)),
output_field=IntegerField()
)
)
ordering = self.request.query_params.get('ordering')
if ordering == …
```
=> 🩹 Fix: 운영 상태에 따른 부스 정렬 추가

linenow/settings.py, requirements.txt
requirements.txt 에서 mysql 관련 내용 삭제
- 쏼라쏼라
```python
```
=> feat: 라인나우 2025 봄 개발 시작

accounts/models.py, linenow/settings.py, waiting/consumers.py, waiting/routing.py, waiting/views.py
waiting websocket 코드 구현 완료 하였습니다.
waiting view 부분 추가중입니다.
(대기 호출, 대기 신청, 대기 취소는 restAPI로 구현 후 websocket으로 실시간 알림이 가도록 구현할 예정입니다.)
User 모델 조금 수정하였습니다.
부스 모델이랑 최신화 되면 postman으로 확인 후 수정사항 있으면 수정하겠습니다.
- 쏼라쏼라
```python
```
=> Feat: websocket 코드 구현 & User model 수정

booth/admin.py, booth/models.py, booth/serializers.py, booth/views.py, manager/admin.py, manager/models.py, manager/serializers.py, manager/urls.py, manager/views.py
Booth 모델 수정 및 개수 api까지 완료했습니다.
Manager, Ask 부분 모델만 수정 완료했습니다.
Booth 사용자 다 완성했는데 집에 가면 마저 pr올릴게요.
- 쏼라쏼라
```python
class Ask(models.Model):
ask_id = models.AutoField(primary_key=True)
question = models.CharField(max_length=100)
answer = models.TextField()
class Manager(models.Model):
manager_id = models.AutoField(primary_key=True)
manager_code = models.CharField(max_length=255, unique=True)
booth = models.OneToOneField(Booth, on_delete=models.CASCADE, related_name='manager')
def __str__(self):
return f'{self.booth.name} 관리자'
def save(self, *args, **kwargs):
if not self.pk:
random_password = ''.join(random.choices(string.ascii_letters + string.digits, k=12))
user = User.objects.create_user(
username=f"manager_{self.booth.name}",
password=random_password  # 랜덤 비밀번호 설정
)
self.user = user
if …
```
=> ✨ Feat: Manager, Ask 모델 수정. Booth 리스트 개수 api 완료

.github/workflows/deploy.yml
=> feat: cicd 파일에서 따옴표 제거

.github/workflows/deploy.yml
=> feat: cicd 실행 조건 수정

booth/serializers.py, booth/views.py, manager/models.py, waiting/models.py
사용자 부스 API 완료했습니다.
부스 정보와 대기 정보 분리해서 api만들었습니다.
- 쏼라쏼라
```python
```
=> ✨ Feat: 사용자 부스 API 완료

requirements.txt
=> feat: requirements.txt 추가

booth/views.py, manager/serializers.py, manager/views.py
관리자 부스 대기 조회 api와 부스 운영 상태 변경 api 구현했습니다.
ManagerViewSet에 함께 작성했습니다. 이전 코드들은 주석 그대로 두었습니다. 
부스 운영 상태 api를 하나로 합쳐서 api명세서 조금 수정했습니다.
- 쏼라쏼라
```python
```
=> ✨ Feat: 관리자 부스 대기 조회, 운영 상태 변경 API 완료

manager/views.py
관리자 권한 여부 확인 부분을 빠뜨려서 추가했습니다!
- 쏼라쏼라
```python
```
=> ⚡️ Fix: 관리자 권한 확인 추가

Dockerfile
=> feat: dockerfile -> daphne 으로 수정

.github/workflows/deploy.yml
=> feat: dockerfile -> 이미지 파일 외부로 복사하도록 설정

booth/views.py
부스 대기 정보 api에서 발생하는 오류 해결했습니다.
- 쏼라쏼라
```python
```
=> 🐛 Fix: 대기 정보 api 오류 해결

.github/workflows/deploy.yml
=> feat: dockerfile -> network 테스트

.github/workflows/deploy.yml
media 폴더 안에 사진이 이상한 경로로 저장이 되어서 cicd 파일을 수정 했습니다.
오류가 발생하여 media 파일을 다시 만든 상태입니다. 기존 사진이 불러와지지 않는 오류가 발생할 수 있습니다.
- 쏼라쏼라
```python
```
=> fix: cicd 파일 수정

.github/backup/backup_deploy.txt, .github/workflows/deploy.yml
무중단 배포를 위한 cicd 파일을 구성하였습니다. 현재 테스트 단계입니다.
- 쏼라쏼라
```python
```
=> feat: blue green 배포 테스트

.github/workflows/deploy.yml
=> feat: cicd 파일 오타 수정

linenow/settings.py
jwt access 토큰 유효 기간을 2일로 제한 했습니다
- 쏼라쏼라
```python
```
=> feat: jwt 유효기간 2일로 제한

booth/serializers.py
부스 api 에서  thumbnail, menu_info 앞에 booth_ 추가했습니다.
- 쏼라쏼라
```python
```
=> 🐛 Fix: 부스 api 필드 이름 수정

Dockerfile
cicd 라인에 celery 컨테이너 실행 코드 추가
```python
```
=> fix: 배포 파이썬 버전 -> 3.12 설정

linenow/settings.py, waiting/views.py
대기 관련 요청에 대한 권한 사용자와 관리자에 따라 권한 부여하였습니다. -> 권한 없으면 요청 불가능하도록 설정해두었습니다.
ssodaa url을 불러오는 코드가 적용되지 않아 해당 부분 수정하였습니다.
- 쏼라쏼라
```python
```
=> Feat: 예외처리

linenow/celery.py, linenow/settings.py, waiting/views.py
문자 전송 코드 오타 수정
- 쏼라쏼라
```python
```
=> Fix: 문자 전송 코드 오타 수정

waiting/views.py
image url request 추가
- 쏼라쏼라
```python
```
=> Fix: my-waiting image url 코드 수정

manager/views.py
manager login 시 operating status 반환 하도록 수정
- 쏼라쏼라
```python
```
=> feat: manager login -> operating status 필드 추가

waiting/views.py
websocket에서 이미지 url 상대경로로 나오는 오류 있어서 절대 경로 반환하도록(base_url 포함되도록) 수정하였습니다.
- 쏼라쏼라
```python
```
=> Fix: websocket 이미지 url 수정

waiting/tasks.py
=> Feat: time_over sms 구현

.github/workflows/deploy.yml
=> feat: cicd -> celery worker 에 redis host 변수 추가

booth/serializers.py
total_waiting_teams 필드를 booths-waiting api에서 booths api로 이동시켰습니다.
- 쏼라쏼라
```python
```
=> 🐛 Fix: total_waiting_teams API 이동

waiting/tasks.py, waiting/views.py
sms 문자 메세지 내용 변경 및 time_over 로직 추가
관리자 websocket user_info 추가
- 쏼라쏼라
```python
```
=> Feat: time_over 대기 취소 로직 추가 & 관리자 websocket user_info 추가

manager/views.py
관리자 페이지 상태별 대기 수, 상태별 대기 api 추가
- 쏼라쏼라
```python
```
=> Feat: 관리자 대기 수, 상태별 대기 get api 추가

manager/views.py
manager login 에 is restart 필드 추가
=> feat: manager login -> is restart 필드 추가

waiting/views.py
=> Feat: 대기 등록 예외처리 추가

waiting/views.py
=> Feat: 대기자 입장 시 다른 대기 전체 취소

waiting/views.py
대기 호출 후 대기 신청 시 대기 되는 오류 수정하였습니다.
- 쏼라쏼라
```python
```
=> Fix: existing waiting 수정

linenow/settings.py
=> Feat: image url https 보이도록 수정

waiting/views.py
나의 대기 리스트에서 입장중->대기중 순서로 정렬되도록 수정했습니다.
- 쏼라쏼라
```python
```
=> 🐛 Fix: 나의 대기 정렬 수정

booth/serializers.py
부스 상세-대기 정보에 현재 요청한 유저의 대기 중인 대기 수와 black list의 user인지 판단하는 field 추가하였습니다.
black list에 포함되면 user_is_black 이 True 반환됩니다.
- 쏼라쏼라
```python
```
=> Feat: 부스 상세 대기 정보 대기 수, black 여부 field 추가

linenow/settings.py
=> Feat: cors 프론트 주소 추가

accounts/views.py
문자 인증코드를 전송할 때 이미 존재하는 번호로는 전송할 수 없도록 변경
=> fix: sms message -> 이미 존재하는 번호로는 전송할 수 없도록 변경

accounts/apps.py, accounts/tasks.py, linenow/settings.py, requirements.txt
=> Feat: no_show_num 초기화 자동화

.github/workflows/deploy.yml
=> feat: celery beat 추가

accounts/tasks.py
=> Fix: no_show_num 초기화 celery 수정

waiting/views.py
문자에 발송되는 주소를 현재 프론트 배포 주소로 수정했습니다.
이후 도메인 배포 시, 재수정할 예정입니다.
- 쏼라쏼라
```python
```
=> Fix: 문자 주소 수정

accounts/views.py, manager/views.py
=> feat: 로그인 시 jwt 토큰 blacklist token 으로 이동하도록 변경

Dockerfile, linenow/settings.py
최대 접속자 수를 늘리기 위한 test 입니다.
오류가 날 수도 있습니다.
- 쏼라쏼라
```python
```
=> feat: 최대 접속자 수 늘리기 위한 worker 수 증가

.github/workflows/deploy.yml, linenow/settings.py
최대 접속자 수를 늘리기 위한 test 입니다.
오류가 날 수도 있습니다.
- 쏼라쏼라
```python
```
=> feat: 최대 접속자 수 늘리기 위한 deploy.yml, settings.py 수정

.github/workflows/deploy.yml
=> fix: pgbouncer 코드 제거

Dockerfile
=> fix: dockerfile 수정

Dockerfile
=> fix: 웹소켓 오류로 daphne 서버로 변경

accounts/serializers.py, accounts/views.py, linenow/settings.py
로그인 회원가입 방식 변경 & 토큰 유효기간 3일로 설정
기존 로그인 방식과 회원가입 방식은 사용하지 않습니다! 명세서를 참고해주세요 (회원가입 방식은 sms code 를 제외하고 전달 받습니다)
- 쏼라쏼라
```python
```
=> 로그인 회원가입 방식 변경 & 토큰 유효기간 3일로 설정

accounts/views.py
회원가입과 로그인 방식을 예전 방식으로 다운그레이드 했습니다
- 쏼라쏼라
```python
```
=> fix: 회원가입, 로그인 ->  예전 버전으로 다운그레이드

accounts/views.py
=> fix: 코드 다운그레이드

accounts/views.py
=> fix: 코드 복구

booth/models.py, waiting/views.py
관리자 연락처 필드 추가, 문자에 전송 기능 추가했습니다.
- 쏼라쏼라
```python
```
=> Feat: 관리자 연락처 필드 추가, 문자에 전송

waiting/views.py
manager_contact 부분을 임시로 None 으로 처리 하였어요
```python
manager_contact = None
if manager_contact != None:
message = f"[라인나우]\n지금 입장하실 차례입니다!\n{booth.booth_name} 부스로 이동해 주세요.\n\n입장 가능 시간은 10분이에요.\n제한 시간 10분 내 입장하지 않으면 전체 대기가 취소돼요.\n\n부스 입장을 원하지 않으신다면,\n반드시 서비스에 접속하여 입장을 취소해주세요.\nhttps://linewnow-test-service.netlify.app/\n\n부스 전화번호: {manager_contact}\n\n※ ‘입장 취소’ 진행 없이 입장하지 않으실 경우\n전체 부스의 대기가 자동 취소돼요.\n또한 노쇼 3회 누적 시, 금일 라인나우 이용이 제한되실 수 있어요."
else:
message = f"[라인나우]\n지금 입장하실 차례입니다!\n{booth.booth_name} 부스로 이동해 주세요.\n\n입장 가능 시간은 10분이에요.\n제한 시간 10분 내 입장하지 않으면 전체 대기가 취소돼요.\n\n부스 입장을 원하지 않으신다면,\n반드시 서비스에 접속하여 입장을 취소해주세요.\nhttps://linewnow-test-service.netlify.app/\n\n※ ‘입장 취소’ 진행 없이 입장하지 않으실 경우\n전체 부스의 대기가 자동 취소돼요.\n또한 노쇼 3회 누적 시, 금일 라인나우 이용이 제한되실 수 있어요."
```
=> fix: LMS 전달 부분 -> manager_contact None 으로 임시 처리

waiting/views.py
주석 추가
```python
manager_contact = None
if manager_contact != None:
message = f"[라인나우]\n지금 입장하실 차례입니다!\n{booth.booth_name} 부스로 이동해 주세요.\n\n입장 가능 시간은 10분이에요.\n제한 시간 10분 내 입장하지 않으면 전체 대기가 취소돼요.\n\n부스 입장을 원하지 않으신다면,\n반드시 서비스에 접속하여 입장을 취소해주세요.\nhttps://linewnow-test-service.netlify.app/\n\n부스 전화번호: {manager_contact}\n\n※ ‘입장 취소’ 진행 없이 입장하지 않으실 경우\n전체 부스의 대기가 자동 취소돼요.\n또한 노쇼 3회 누적 시, 금일 라인나우 이용이 제한되실 수 있어요."
else:
message = f"[라인나우]\n지금 입장하실 차례입니다!\n{booth.booth_name} 부스로 이동해 주세요.\n\n입장 가능 시간은 10분이에요.\n제한 시간 10분 내 입장하지 않으면 전체 대기가 취소돼요.\n\n부스 입장을 원하지 않으신다면,\n반드시 서비스에 접속하여 입장을 취소해주세요.\nhttps://linewnow-test-service.netlify.app/\n\n※ ‘입장 취소’ 진행 없이 입장하지 않으실 경우\n전체 부스의 대기가 자동 취소돼요.\n또한 노쇼 3회 누적 시, 금일 라인나우 이용이 제한되실 수 있어요."
```
=> fix: LMS 전달 부분 -> manager_contact None 으로 임시 처리하고 주석 처리

booth/models.py, waiting/views.py
부스 연락처 부분 다시 추가했습니다.
- 쏼라쏼라
```python
```
=> Fix: 부스 연락처 추가

linenow/settings.py
=> feat: 프론트 배포 주소 cors 부분 추가

accounts/views.py
전체 유저 수 확인 로직 추가
- 쏼라쏼라
```python
```
=> feat: 전체 유저 수 확인 로직 추가

accounts/models.py, accounts/views.py
문자 인증 코드 3분 제한
- 쏼라쏼라
```python
```
=> feat: 문자 인증 코드 3분 제한

accounts/views.py
SMS -> sms 오타 수정
- 쏼라쏼라
```python
```
=> fix: 문자 전송 방식 오타 수정

.github/workflows/deploy.yml
=> fix: deploy 에서 주석 제거

linenow/settings.py
=> Feat: image url https로 변경

booth/serializers.py
부스 이미지를 id 값 순서대로 내보내도록 시리얼라이저 수정
지윤이 파트를 대신 수정했어요
=> fix: 부스 이미지 순서대로 내보내도록 설정

.github/workflows/deploy.yml
=> fix: cicd docker pull 하게 변경

booth/serializers.py
=> feat: 부스 메뉴도 id 로 정렬하게 변경

manager/views.py
관리자뷰에서 필터별 대기 정렬 수정했습니다.
- 쏼라쏼라
```python
```
=> Fix: 관리자뷰 대기 정렬 수정
